//1. Difference between package.json and package-lock.json
// package.json - Stores project details
// package-lock.json - Stores exact dependency versions
// package.json - Manually created & editable
// package-lock.json - Auto-generated by npm

//2. Difference between Dev dependencies and dependencies
// dependencies - Required to run the application
// devDependencies - Required only during development

//3. routes creation and use js in that
const express = require("express");
const app = express();

app.get("/", (req, res) => {
  res.send("Home Page");
});

app.get("/about", (req, res) => {
  res.send("About Page");
});

app.listen(3000);

const express = require("express");
const router = express.Router();

router.get("/", (req, res) => {
  res.send("User List");
});

module.exports = router;

//4. types of HTTP methods GET, PUT, POST, DELETE
// GET	-Fetch data
// POST	-Create data
// PUT	-Update full data
// DELETE	-Delete data


//Middleware
//1. Why we use middleware ?
// Modify request/response
// Add security
// Log data
// Validate input

//2.	What are the types of middleware ?
// Application middleware
// Router middleware
// Error-handling middleware

//3.	What are the benefits of middleware ?
// Code reuse
// Better structure
// Security handling
//  Easy debugging

//4.	Where the middleware is used in company level ?
// Authentication (login check)
// Logging (user activity)
// API validation
// Error handling

//Query parameter

//1.	What are the query parameters ?
//Extra data sent in URL after
//2.	detail study about query parameter
// Stored in req.query
// Used for filtering, searching
// Optional parameters
//3.	3-4 examples of query parameters
// /products?category=mobile
// /users?age=20
// /books?author=xyz
// /search?q=java
//4.	real time use of query parameter
// E-commerce filters (price, category)
// Search bar

//Template Engine 
//1.	Implement EJS
//npm install ejs
//app.set("view engine", "ejs");
//<h1>Hello <%= name %></h1>
//app.get("/", (req, res) => {
//   res.render("index", { name: "Aditi" });
// });


//2.	What are static files ?
//Static files = files that don’t change:

//3.	What is express router ?
//Separate code
//Manage routes easily

//4.	Complete express workflow
// User sends request (browser/Postman)
// Request reaches Express server
// Middleware runs (logging, auth)
// Route matches URL
// Controller logic runs
// Data processed (DB/API)
// Response sent to client